management:
    endpoints:
        web:
            exposure:
                exclude: 'env,loggers,beans'
                include: '*'
server:
    port: 8021
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: password
        url: jdbc:mysql://localhost:3306/sqldatabase
        username: user
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        
welcome:
    msg: hi guys welocme im learning spring boot